// Generated by gencpp from file gazebo_ros_link_attacher/Attach.msg
// DO NOT EDIT!


#ifndef GAZEBO_ROS_LINK_ATTACHER_MESSAGE_ATTACH_H
#define GAZEBO_ROS_LINK_ATTACHER_MESSAGE_ATTACH_H

#include <ros/service_traits.h>


#include <gazebo_ros_link_attacher/AttachRequest.h>
#include <gazebo_ros_link_attacher/AttachResponse.h>


namespace gazebo_ros_link_attacher
{

struct Attach
{

typedef AttachRequest Request;
typedef AttachResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Attach
} // namespace gazebo_ros_link_attacher


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::gazebo_ros_link_attacher::Attach > {
  static const char* value()
  {
    return "c91fb3be70ce66d19130d40294cf4bd5";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Attach&) { return value(); }
};

template<>
struct DataType< ::gazebo_ros_link_attacher::Attach > {
  static const char* value()
  {
    return "gazebo_ros_link_attacher/Attach";
  }

  static const char* value(const ::gazebo_ros_link_attacher::Attach&) { return value(); }
};


// service_traits::MD5Sum< ::gazebo_ros_link_attacher::AttachRequest> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Attach >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::AttachRequest>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Attach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::AttachRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::AttachRequest> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Attach >
template<>
struct DataType< ::gazebo_ros_link_attacher::AttachRequest>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Attach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::AttachRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::gazebo_ros_link_attacher::AttachResponse> should match
// service_traits::MD5Sum< ::gazebo_ros_link_attacher::Attach >
template<>
struct MD5Sum< ::gazebo_ros_link_attacher::AttachResponse>
{
  static const char* value()
  {
    return MD5Sum< ::gazebo_ros_link_attacher::Attach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::AttachResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::gazebo_ros_link_attacher::AttachResponse> should match
// service_traits::DataType< ::gazebo_ros_link_attacher::Attach >
template<>
struct DataType< ::gazebo_ros_link_attacher::AttachResponse>
{
  static const char* value()
  {
    return DataType< ::gazebo_ros_link_attacher::Attach >::value();
  }
  static const char* value(const ::gazebo_ros_link_attacher::AttachResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAZEBO_ROS_LINK_ATTACHER_MESSAGE_ATTACH_H
