
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  shoulder_pan_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0} #original value: p: 500.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0
  shoulder_lift_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 500.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0} #original value: p: 500.0, i: 100.0, d: 30.0, i_clamp_min: -400.0, i_clamp_max: 400.0
  elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 10000.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0} #original value: p: 10000.0, i: 0.01, d: 50.0, i_clamp_min: -100.0, i_clamp_max: 100.0
  wrist_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -400.0, i_clamp_max: 400.0} #original value: p: 200.0, i: 10.0, d: 20.0, i_clamp_min: -400.0, i_clamp_max: 400.0
  wrist_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0} #original value: p: 100.0, i: 0.1, d: 10.0, i_clamp_min: -100.0, i_clamp_max: 100.0
  wrist_3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 40.0, i: 0.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0} #original value: p: 40.0, i: 0.0, d: 0.0, i_clamp_min: -100.0, i_clamp_max: 100.0
  gripper_controller:
    type: position_controllers/GripperActionController
    joint: robotiq_85_left_knuckle_joint
    action_monitor_rate: 20
    goal_tolerance: 0.002
    max_effort: 100
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0
  #gripper_position_controller:
    #type: effort_controllers/JointPositionController
    #joint: robotiq_85_left_knuckle_joint
    #pid: {p: 40.0, i: 0.0, d: 0.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    #pid_gains: {p: 50.0, i: 0.5, d: 0.0, i_clamp_min: -10.0, i_clamp_max: 10.0}

  #pid_gains:
   # robotiq_85_left_knuckle_joint:
    #  p: 40.0
     # i: 0.0
      #d: 0.0
#/robotName/gazebo_ros_controls/pid_gains:
#..joint1: {p: 10.0,i: 0.0, d:0.01}